/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PatientSettingsRouteImport } from './routes/patient/settings'
import { Route as PatientRecordsRouteImport } from './routes/patient/records'
import { Route as PatientPredictionsRouteImport } from './routes/patient/predictions'
import { Route as PatientMedicationsRouteImport } from './routes/patient/medications'
import { Route as PatientBrainRouteImport } from './routes/patient/brain'
import { Route as PatientAssistantRouteImport } from './routes/patient/assistant'
import { Route as PatientAppointmentsRouteImport } from './routes/patient/appointments'
import { Route as PatientAnalyticsRouteImport } from './routes/patient/analytics'
import { Route as DoctorSettingsRouteImport } from './routes/doctor/settings'
import { Route as DoctorReportsRouteImport } from './routes/doctor/reports'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor/prescriptions'
import { Route as DoctorPredictionsRouteImport } from './routes/doctor/predictions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor/patients'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor/appointments'
import { Route as DoctorAnalyticsRouteImport } from './routes/doctor/analytics'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminClinicsRouteImport } from './routes/admin/clinics'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientRecordsRoute = PatientRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientPredictionsRoute = PatientPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientMedicationsRoute = PatientMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientBrainRoute = PatientBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientAnalyticsRoute = PatientAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PatientRouteRoute,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorReportsRoute = DoctorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPredictionsRoute = DoctorPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorAnalyticsRoute = DoctorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/predictions': typeof DoctorPredictionsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/analytics': typeof PatientAnalyticsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/brain': typeof PatientBrainRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/predictions': typeof PatientPredictionsRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/predictions': typeof DoctorPredictionsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/analytics': typeof PatientAnalyticsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/brain': typeof PatientBrainRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/predictions': typeof PatientPredictionsRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/predictions': typeof DoctorPredictionsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/analytics': typeof PatientAnalyticsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/brain': typeof PatientBrainRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/predictions': typeof PatientPredictionsRoute
  '/patient/records': typeof PatientRecordsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/auth'
    | '/admin/analytics'
    | '/admin/clinics'
    | '/admin/doctors'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/settings'
    | '/admin/users'
    | '/api/chat'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/doctor/predictions'
    | '/doctor/prescriptions'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/patient/analytics'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/brain'
    | '/patient/medications'
    | '/patient/predictions'
    | '/patient/records'
    | '/patient/settings'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/analytics'
    | '/admin/clinics'
    | '/admin/doctors'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/settings'
    | '/admin/users'
    | '/api/chat'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/doctor/predictions'
    | '/doctor/prescriptions'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/patient/analytics'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/brain'
    | '/patient/medications'
    | '/patient/predictions'
    | '/patient/records'
    | '/patient/settings'
    | '/admin'
    | '/doctor'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/auth'
    | '/admin/analytics'
    | '/admin/clinics'
    | '/admin/doctors'
    | '/admin/logs'
    | '/admin/models'
    | '/admin/settings'
    | '/admin/users'
    | '/api/chat'
    | '/doctor/analytics'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/doctor/predictions'
    | '/doctor/prescriptions'
    | '/doctor/reports'
    | '/doctor/settings'
    | '/patient/analytics'
    | '/patient/appointments'
    | '/patient/assistant'
    | '/patient/brain'
    | '/patient/medications'
    | '/patient/predictions'
    | '/patient/records'
    | '/patient/settings'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/records': {
      id: '/patient/records'
      path: '/records'
      fullPath: '/patient/records'
      preLoaderRoute: typeof PatientRecordsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/predictions': {
      id: '/patient/predictions'
      path: '/predictions'
      fullPath: '/patient/predictions'
      preLoaderRoute: typeof PatientPredictionsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/medications': {
      id: '/patient/medications'
      path: '/medications'
      fullPath: '/patient/medications'
      preLoaderRoute: typeof PatientMedicationsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/brain': {
      id: '/patient/brain'
      path: '/brain'
      fullPath: '/patient/brain'
      preLoaderRoute: typeof PatientBrainRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/analytics': {
      id: '/patient/analytics'
      path: '/analytics'
      fullPath: '/patient/analytics'
      preLoaderRoute: typeof PatientAnalyticsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/reports': {
      id: '/doctor/reports'
      path: '/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof DoctorReportsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/predictions': {
      id: '/doctor/predictions'
      path: '/predictions'
      fullPath: '/doctor/predictions'
      preLoaderRoute: typeof DoctorPredictionsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminClinicsRoute: AdminClinicsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DoctorRouteRouteChildren {
  DoctorAnalyticsRoute: typeof DoctorAnalyticsRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPredictionsRoute: typeof DoctorPredictionsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorReportsRoute: typeof DoctorReportsRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorAnalyticsRoute: DoctorAnalyticsRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPredictionsRoute: DoctorPredictionsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorReportsRoute: DoctorReportsRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

interface PatientRouteRouteChildren {
  PatientAnalyticsRoute: typeof PatientAnalyticsRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientBrainRoute: typeof PatientBrainRoute
  PatientMedicationsRoute: typeof PatientMedicationsRoute
  PatientPredictionsRoute: typeof PatientPredictionsRoute
  PatientRecordsRoute: typeof PatientRecordsRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientAnalyticsRoute: PatientAnalyticsRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientAssistantRoute: PatientAssistantRoute,
  PatientBrainRoute: PatientBrainRoute,
  PatientMedicationsRoute: PatientMedicationsRoute,
  PatientPredictionsRoute: PatientPredictionsRoute,
  PatientRecordsRoute: PatientRecordsRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
